name = "ai-playground"
main = "src/worker.js"
compatibility_date = "2024-04-18"
compatibility_flags=["nodejs_compat"]

[ai]
binding = "AI"

[vars]
COMPOSIO_API_KEY = "{{COMPOSIO_API_KEY}}"
OPENAI_API_KEY = "{{OPENAI_API_KEY}}"